# Use the official Ubuntu as the base image
FROM ubuntu:latest

# Update the package lists, install essential packages, and clean up
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    maven \
    && rm -rf /var/lib/apt/lists/*

# Add the current directory (.) to the PATH environment variable
ENV PATH="${PATH}:."

# Set the working directory
WORKDIR /root

# Start a Bash shell when the container is run
CMD ["/bin/bash"]